[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#31333F"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000

[server]
enableXsrfProtection = false
enableCORS = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
