[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
height = 600
width = 800

[ui.select]
height = 40
width = 200
fontSize = 16
backgroundColor = "#FFFFFF"
textColor = "#262730"
borderColor = "#E0E0E0"
borderWidth = 1
borderRadius = 4
padding = 8

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000

[server]
enableXsrfProtection = false
enableCORS = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
